schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master

variables:
  resourceGroupName: 'manx-stable'

jobs:
- job: Doit
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: UsePythonVersion@0
    displayName: Use Python 3.6
    inputs:
      versionSpec: '3.6'

  - task: AzureCLI@2
    displayName: Provision, Deploy and run tests
    inputs:
      azureSubscription: AzureSubscription
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        cd $(Build.SourcesDirectory)/libraries/functional-tests/functionaltestbot
        chmod +x ./scripts/deploy_webapp.sh
        ./scripts/deploy_webapp.sh --appid $(botAppId) --password $(botAppPassword) -g $(resourceGroupName)
    continueOnError: false
